Azure/accelerator-bootstrap-modules

.github/tests/scripts/Install-AcceleratorModule.ps1, .github/workflows/end-to-end-test.yml
Add an input for workflow_dispatch to select the PS module branch and default to main
N/A
None
e2e tests run
=> Default to main and provide override

alz/.config/ALZ-Powershell.config.json, alz/azuredevops/terraform.tfvars, alz/github/terraform.tfvars
Fixes a typo and updates the container image source.
None
None
e2e tests run.
=> enhancement: update container image location

.github/workflows/end-to-end-test.yml
There is an error when the tests are triggered by the schedule. Attempting to fix that error.
N/A
N/A
e2e tests run
=> Fix e2e tests

modules/github/locals.tf
=> bug: fix runner group logic

alz/azuredevops/terraform.tfvars
Add the `--once` flag to make the agents ephemeral
1. https://github.com/Azure/alz-terraform-accelerator/issues/88
None
=> enhancement: upgrade to ephemeral agent image for azure devops

.github/workflows/release.yml
=> tidy action

.github/workflows/release.yml
=> Flatten archive

.config/ALZ-Powershell.config.json
Allow specifying a release artefact name.
None
None
=> Add release artifact config

.config/ALZ-Powershell.config.json
=> Update starter module folder paths to work with new model

.config/ALZ-Powershell.config.json
=> Add config file path

.config/ALZ-Powershell.config.json
=> add short name config

.github/workflows/end-to-end-test.yml
=> Update starter name

.config/ALZ-Powershell.config.json, .github/workflows/release.yml
=> Fix artifact spelling

alz/local/variables.hidden.tf
Update custom ALZ roles for subscription scoped roles to include `Microsoft.SecurityInsights/onboardingStates/write`
Fixes #30 
1. Add `Microsoft.SecurityInsights/onboardingStates/write` to ALZ-Bicep custom roles
1. None
=> Add onboarding write permissions

alz/azuredevops/locals.tf, alz/azuredevops/main.tf, alz/github/locals.tf, alz/github/main.tf
1. https://github.com/Azure/ALZ-PowerShell-Module/issues/151
None, the existing combination was not valid anyway
e2e tests
=> Bug: Only public networking is allowed with Microsoft-Hosted agents / runners

.github/tests/scripts/destroy.ps1, .github/workflows/end-to-end-test.yml
=> Fix destroy file trigger

.github/policies/resourceManagement.yml
Remove unneeded policies for resource management.
1. Remove unneeded policies for resource management.
1. None
=> fix: Remove unneeded policies

modules/azure/variables.tf
Microsoft.TimeSeriesInsights has been removed from Azure and is causing errors.
1. https://github.com/Azure/ALZ-PowerShell-Module/issues/191
None
=> fix: remove redundant resource provider

alz/.config/ALZ-Powershell.config.json, alz/azuredevops/main.tf, alz/azuredevops/variables.hidden.tf, alz/github/main.tf, alz/github/variables.hidden.tf, alz/local/main.tf, alz/local/variables.hidden.tf, modules/files/main.tf, modules/files/variables.tf
This PR is part of the multi region support for Terraform.
N/A
Backwards compatible
e2e tests: https://github.com/Azure/accelerator-bootstrap-modules/actions/runs/11056162578
=> feat: multi region support for terraform

.config/ALZ-Powershell.config.json
Adds support for multi-region deployments in ALZ-Bicep
=> feat: add hubNetworkingMultiRegion validation

.github/workflows/release.yml
Fixes the trigger for publishing release artifacts
N/A
N/A
=> chore: fix trigger for artifacts

alz/local/variables.hidden.tf
Fix the default folder level for local output
N/A
None
=> fix: default local output folder

alz/local/main.tf
Improve the local Terraform experience by outputting a script as per Bicep.
N/A
N/A
=> feat: add local script file for terraform

modules/template_architecture_definition/locals.tf, modules/template_architecture_definition/templates/slz.alz_architecture_definition.json.tftpl
feat: Move the architecture template in.
1. Move the architecture template in.
1. Move the architecture template in.
=> feat: Move the architecture template in.

alz/azuredevops/locals.tf, alz/azuredevops/variables.hidden.tf, alz/github/locals.tf, alz/github/variables.hidden.tf, alz/local/locals.tf, alz/local/variables.hidden.tf
Updates to support Sovereign Landing Zone starter module.
N/A
None
=> feat: add sovereign landing zone

alz/local/locals.tf
Fixes a bug for none SLZ modules in local file system mode
N/A
None
=> fix: null architecture_definition_name in local

alz/azuredevops/pipelines/terraform/templates/helpers/terraform-apply.yaml, alz/github/actions/terraform/templates/workflows/cd-template.yaml
1. https://github.com/Azure/terraform-azurerm-avm-ptn-alz/issues/157
2. https://github.com/Azure/ALZ-PowerShell-Module/issues/269
None, timeouts only
=> fix: management group get after create timeout

alz/azuredevops/terraform.tf, alz/github/terraform.tf, alz/local/terraform.tf, modules/azure/terraform.tf, modules/azure_devops/terraform.tf, modules/github/terraform.tf
Update provider versions and block unnessesary data plane operations on the storage account
1. https://github.com/Azure/ALZ-PowerShell-Module/issues/305
None
=> feat: update provider versions and stop data plane actions on storage account

alz/azuredevops/pipelines/terraform/templates/helpers/terraform-installer.yaml
Resolve a HashiCorp upstream API change
N/A
None
=> fix: terraform installer

modules/azure/storage.tf
Attempt to fix an issue with state file and storage data plan resources...
N/A
None
=> fix: storage data plane and state file issues

alz/github/main.tf, alz/github/variables.tf, modules/github/locals.tf, modules/github/variables.tf
Support for the ghe.com domain.
N/A
None
=> feat: support ghe.com

.github/tests/scripts/generate-matrix.ps1, .github/workflows/end-to-end-test.yml, alz/github/locals.tf, alz/github/main.tf, alz/github/terraform.tf, alz/github/variables.tf, modules/github/locals.tf, modules/github/outputs.tf, modules/github/variables.tf
In order to support ghe.com we need to supply the base api url. This PR refactors the code to support that while defaulting to GitHub.com
It also fixes the SLZ tests
N/A
None
=> fix: api base url

modules/azure_devops/groups.tf, modules/github/team.tf
Add approver validation to throw an error if they do not exist
Fixes: https://github.com/Azure/ALZ-PowerShell-Module/issues/345
None
=> feat: validation of approvers

alz/github/main.tf, modules/github/outputs.tf, modules/github/variables.tf
Support ghe.com OIDC issuer
None
N/A
=> feat: support ghe.com oidc issuer

modules/github/repository_templates.tf
Release branch for: https://github.com/Azure/accelerator-bootstrap-modules/pull/97
Fixes: https://github.com/Azure/ALZ-PowerShell-Module/issues/365
None
=> fix: github actions repository access level for private repositories

.github/workflows/release.yml
Releaser broken, temporary fix to use older task version.
Issue: https://github.com/softprops/action-gh-release/issues/628
=> fix: release issue

.github/workflows/end-to-end-test.yml
Update e2e tests for Bicep to support subscription map
N/A
None
=> feat: security mg for bicep
