- .github/workflows/end-to-end-test.yml
- alz/azuredevops/main.tf
- alz/azuredevops/variables.input.tf
Support separate PAT for Azure DevOps Agents. This allows for a longer expiry. This is a pre-requisite for ephemeral agents, but will help existing customers now.
1. https://github.com/Azure/alz-terraform-accelerator/issues/88
None
e2e tests run
> enhancement: azure devops agent separate pat

- alz/azuredevops/pipelines/bicep/templates/helpers/bicep-on-demand-folder.yaml
- alz/github/actions/bicep/templates/actions/bicep-on-demand-folder/action.yaml
Fix issue with e2e tests to support `latest` tag in GitHub
> Bug fix for on demand folder latest for tests

- alz/azuredevops/locals.files.tf
- alz/azuredevops/locals.tf
- alz/azuredevops/main.tf
- alz/azuredevops/variables.hidden.tf
- alz/github/locals.files.tf
- alz/github/locals.tf
- alz/github/main.tf
- alz/github/variables.hidden.tf
- alz/local/locals.tf
- alz/local/main.tf
- alz/local/variables.hidden.tf
- modules/files/main.tf
- modules/files/variables.tf
- modules/template_architecture_definition/data.tf
- modules/template_architecture_definition/locals.tf
- modules/template_architecture_definition/outputs.tf
- modules/template_architecture_definition/terraform.tf
- modules/template_architecture_definition/variables.tf
Adding architecture definition module for FSI/SLZ, and additional_folders, enable_alz, and architecture_definition_path hidden variables
1. Adds support for including additional folders to repo
2. Adds architecture definition creation module
3. Adds hidden variables to include alz archetypes in architecture definition template file(enable_alz), architecture definition file path(architecture_definition_path), and include additional folders in repo(additional_folders)
1. None
> feat: Adding architecture definition module and additional folders variable

- alz/azuredevops/main.tf
- alz/azuredevops/variables.hidden.tf
- alz/github/main.tf
- alz/github/variables.hidden.tf
- alz/local/main.tf
- alz/local/variables.hidden.tf
- modules/template_architecture_definition/data.tf
- modules/template_architecture_definition/locals.tf
- modules/template_architecture_definition/outputs.tf
- modules/template_architecture_definition/variables.tf
Adds feature request https://github.com/Azure/ALZ-PowerShell-Module/issues/186
1. Uses starter module tfvars for inputs to template architecture definition module
2. Adds input for architecture_definition_template_path
3. Renaming template architecture definition variables, removing from variables.hidden.tf
1. None
> feat: Using starter module tfvars for architecture definition inputs

- alz/azuredevops/variables.hidden.tf
- alz/github/variables.hidden.tf
- alz/local/variables.hidden.tf
Fixes https://github.com/Azure/ALZ-PowerShell-Module/issues/183
Fixes https://github.com/Azure/ALZ-PowerShell-Module/issues/185
1. Adds write permissions to onboardingStates
2. Adds write and delete authorization permissions for subscription plaecment module
3. Remove unneeded onboardingStates write permission and management group scope for local
1. None
> fix: Bicep permissions for what-if

- alz/azuredevops/variables.hidden.tf
- alz/github/variables.hidden.tf
- alz/local/variables.hidden.tf
Fixes [#188](https://github.com/Azure/ALZ-PowerShell-Module/issues/188)
1. Adds "Microsoft.Insights/diagnosticSettings/write" to mgmt group contributor
2. Adds "Microsoft.Authorization/policyAssignments/write" to mgmt group contributor
1.None
> fix: Add additional permissions for bicep deployment permissions

- modules/template_architecture_definition/locals.tf
Confidential archetypes should contain confidential and optionally the corresponding ALZ archetype
1. confidential online/corp archtypes in architecture defintion module
1. None
> fix: Updating confidential archetypes

- alz/azuredevops/variables.hidden.tf
- alz/github/variables.hidden.tf
- alz/local/variables.hidden.tf
Add permissions required to read a deployment template for the legacy telemetry provider
1. https://github.com/Azure/ALZ-PowerShell-Module/issues/241
None
> fix: add roles for legacy telemetry provider

- .github/workflows/end-to-end-test.yml
- alz/azuredevops/locals.tf
- alz/azuredevops/terraform.tf
- alz/azuredevops/variables.hidden.tf
- alz/github/locals.tf
- alz/github/terraform.tf
- alz/github/variables.hidden.tf
- alz/local/terraform.tf
- modules/azure/container_instances.tf
- modules/azure/data.tf
- modules/azure/terraform.tf
This PR fixes an issue identified in some regions that don't have availability zone support.
1. https://github.com/Azure/ALZ-PowerShell-Module/issues/187
None
> fix: agent container zone support

- .gitignore
- alz/azuredevops/variables.input.tf
- alz/azuredevops/variables.interface.tf
- alz/github/variables.input.tf
- alz/github/variables.interface.tf
- alz/local/terraform.tfvars
- alz/local/variables.input.tf
- alz/local/variables.interface.tf
This PR adds some validation for bootstrap inputs that previously had it for the UI inputs.
1. https://github.com/Azure/ALZ-PowerShell-Module/issues/261
None
> fix: add validation to bootstrap inputs

- .github/workflows/docs-fmt-test.yml
- alz/azuredevops/terraform.tf
- modules/azure_devops/terraform.tf
This is a workaround for a breaking change in 1.5 of the azuredevops provider.
- https://github.com/Azure/ALZ-PowerShell-Module/issues/266
None
> fix: pin azure devops provider version

- alz/azuredevops/locals.tf
- alz/azuredevops/main.tf
- alz/azuredevops/variables.hidden.tf
- alz/github/locals.tf
- alz/github/main.tf
- alz/github/variables.hidden.tf
- alz/local/locals.tf
- alz/local/main.tf
- alz/local/variables.hidden.tf
- modules/files/main.tf
- modules/files/variables.tf
- modules/template_architecture_definition/locals.tf
Add some checks in case config is missing
1. https://github.com/Azure/ALZ-PowerShell-Module/issues/267
None
> fix: missing slz fsi input

- alz/azuredevops/pipelines/terraform/main/cd.yaml
- alz/azuredevops/pipelines/terraform/main/ci.yaml
- alz/azuredevops/pipelines/terraform/templates/cd-template.yaml
- alz/azuredevops/pipelines/terraform/templates/ci-template.yaml
- alz/azuredevops/pipelines/terraform/templates/helpers/terraform-installer.yaml
- alz/github/actions/terraform/main/workflows/cd.yaml
- alz/github/actions/terraform/main/workflows/ci.yaml
- alz/github/actions/terraform/templates/workflows/cd-template.yaml
- alz/github/actions/terraform/templates/workflows/ci-template.yaml
- modules/azure/storage.tf
1.11 of Terraform Core introduced a breaking change to the azurerm backend. https://github.com/hashicorp/terraform/issues/36595
Adding the ability to override the Terraform CLI version for easy testing. 
Temporarily granting reader access to the storage account.
None
None
> fix: temporary allow reader access to storage account for 1.11 permissions issue

- alz/azuredevops/locals.files.tf
- alz/github/locals.files.tf
Update the path to the `architecture_definition_file` to be created under `<module_path>/lib`
1. [Bug: Azure DevOps terraform provider ALZ fails to load custom_url from /lib](https://github.com/Azure/ALZ-PowerShell-Module/issues/316)
N/A
In progress
> feat: Fix path for architecture_definition_file

- alz/local/templates/terraform-deploy-local.ps1
IaC: terraform
Starter module: SLZ
Deploying locally.
If a user first installs with inputs.yaml/create_bootstrap_resources_in_azure = false - in error - and then later decides to set that flag to true, the local tf state should be migrated to remote state.
1. Adds -migrate-state flag to the tf init step in deploy-local.ps1 if use_remote_state is detected
None
I tested 2 use cases:
1. first run after a local deployment where local state exists and remote state settings are detected. It correctly migrates the state to remote backend.
2. second run once the state has been migrated. It correctly ignores the -migrate-state flag.
> feat: add the migrate state flag if using remote state

- alz/azuredevops/variables.tf
- alz/github/variables.tf
- alz/local/variables.tf
- modules/azure/variables.tf
Remove the storage account replication validation and just default tom ZRS. This is to support regions with no AZ support for storage, such as Canada East.
N/A
None
> feat: remove storage account replication validation

- alz/azuredevops/variables.tf
- alz/github/variables.tf
- alz/local/variables.tf
…settings
On a new Landing Zone deployment and noticed that the automation consistently got hung up on creating management group hierarchy settings until it timed out. I could not see anything happening on the activity log of the tenant root management group. I suspected the issue may be RBAC related so we updated the **Azure Landing Zones Management Group Contributor** role definition to include the "Microsoft.Management/managementGroups/settings/read" and "Microsoft.Management/managementGroups/settings/write" permissions and the deployment immediately created the settings and continued as expected. Likewise, for the **Azure Landing Zone Management Group Reader** I added the read permissions to the Azure Landing Zones Management Group Reader role.
1. Update the Azure Landing Zone …
> feat(alz/azuredevops): update ALZ management group RBAC role definitions

- alz/github/variables.tf
- modules/github/team.tf
Allow searching for GitHub users by username or email.
1. https://github.com/Azure/ALZ-PowerShell-Module/issues/349
None
> feat: support looking up github user by username

- alz/azuredevops/variables.tf
- alz/github/variables.tf
- alz/local/variables.tf
…Azure resources to correct deployment failures using terraform
Currently the terraform alz_management_group_contributor role does not possess sufficient permissions to deploy custom roles and custom policies. This request aligns this role with the bicep contributor which does have the correct permissions as per [341](https://github.com/Azure/ALZ-PowerShell-Module/issues/341)
Resolves issues whereby the custom role for terraform apply does not contain sufficient permissions to create the roles and policies required by the accelerator
None
Giving the apply MI owner rights to the root management group allows the roles and policies to be created. Modifying the custom role with the bicep permissions also allows this to function correctly.
> feat: extend custom role definitions with additional permissions for terraform

- .github/tests/scripts/destroy.ps1
- .github/workflows/end-to-end-test.yml
- alz/azuredevops/variables.tf
- alz/github/variables.tf
Support for ghe.com in the upstream docker image for self hosted agents.
Associated dockerfile update: https://github.com/Azure/avm-container-images-cicd-agents-and-runners/compare/bc4087f022e4c0e253a0ac8d7313bfabce0eed94...39b9059a5b847381d6c9c756cc9cc22540899a7f#diff-8a2c08102e431cbbf7c60d7181dcfcbfe699b04661501da2cf8d24c16ce684bf
N/A
None
> feat: support ghe.com in self hosted agent

- alz/github/actions/terraform/templates/workflows/cd-template.yaml
- alz/github/actions/terraform/templates/workflows/ci-template.yaml
- alz/github/locals.files.tf
Set the uses: value correctly when using single repo in combincation with Terraform and GitHub.
Replicates the logic used for azuredevops / terraform, and applies it to github / terraform.
1 [#391](https://github.com/Azure/ALZ-PowerShell-Module/issues/391)
Tested on bootstrap in pwsh on Ubuntu 24.04, and then ran the two workflows.
> fix: Correct repository_name_templates when using single repo

- alz/azuredevops/main.tf
- alz/azuredevops/variables.tf
- alz/github/main.tf
- alz/github/variables.tf
- alz/local/main.tf
- alz/local/variables.tf
- modules/azure/storage.tf
- modules/azure/variables.tf
Turn on soft delete and versioning by default and make it configurable.
N/A
None
> feat: storage account soft delete
